### PR TITLE
Support for Windows Phone 8.1.

### PR DESCRIPTION
**Pull request by josea**
Modification for the nuspec so it has the correct reference to the platform DLL for wp81.

### CODE REVIEW

**Comment by aritchie** [comment]
Thanks

**Comment by josea** [comment]
Not a problem. Did you resolve it in another way for WP81? (I just downloaded version 2.1.2 and it still doesn't seem to work in WP81). Thanks.

**Comment by aritchie** [comment]
The sample runs for me, so you'll have to give me a better idea of what doesn't work.

**Comment by josea** [comment]
You do not have a WinPhone81 sample (project properties\application\target  windows phone os version = Windows Phone 8.1.).

**Comment by aritchie** [comment]
I have a super sample that has one.  What is the exact issue you are having?  Nuget package not installing?  Is there an error?  Do you have a stack trace?

**Comment by josea** [comment]
The main issue is "Platform implementation not found.  Have you added a nuget reference to your platform project?" when calling Acr.DeviceInfo.DeviceInfo.Instance.AppVersion.  Stack trace below (I have added the nugget reference to the platform project).

Please note that my project doesn't want to download the 2.1.2 version of your nuget - the version that it sees is 2.1.0. I guess this is due a mismatch between my target profile and the target profile of v2.1.1 and v2.1.2. This is happening also for the sample project in your repository (I cloned it, added the Acr.DeviceInfo nuget, but it won't download the 2.1.2, only 2.1.0). 

These projects are targetting .NET 4.5, Win8, WP81, WP Silverlight8, Xamarin.Android, Xamarin.iOS and Xamarin.iOS (classic).  

Is your supersample public? maybe I can take a look at it. Thanks.

   at Acr.DeviceInfo.DeviceInfo.get_Instance()
   at Scanpack.net.MainScreenView.get_AppVersion()
   at Scanpack.net.MainScreenView..ctor()
   at Scanpack.net.App.GetMainPage()
   at Scanpack.net.App.LaunchMainPage()
   at Scanpack.net.App.Initialize()
   at Scanpack.net.App.get_Instance()
   at WindowsXamarinFormsApp1.WinPhone.MainPage..ctor()

**Comment by josea** [comment]
BTW: I checked the .csproj file, and the target profile is 259. Still, that project doesn't see v2.1.2 of the nuget.

```
<TargetFrameworkProfile>Profile259</TargetFrameworkProfile>
```

**Comment by aritchie** [comment]
This is an issue with the nuspec that is updated today with 2.2.  My windows common plug points were wrong.

**Comment by josea** [comment]
Thanks. I'll try it on my side and let you know if there are still issues. Thanks again.

**Comment by josea** [comment]
Just a quick note to let you know that I finally tested it and it is working fine. Thanks.

**Pull request closed without merging**
